App 1422 input text
bureaux-a-partager/morning-react-ui pull request #12
Opened 2024-03-04 10:52 UTC by LouiseLeroux1992

input text with options :
- image
- error
- disabled

2024-03-04 13:08 UTC, Casimor approved these changes

2024-03-04 16:57 UTC, dellamowica approved these changes

2024-03-05 10:02 UTC, Archors requested changes

2024-03-05 10:02 UTC, Archors commented on components/inputs/parentInput.module.css
Pas le même ticket mais tant qu'a faire peut être bien formatter le truc comme en CSS classique

2024-03-05 11:33 UTC, LouiseLeroux1992 commented on components/inputs/inputText.module.css
oui haha en effet j'ai fait ça dans la branche de l'input number ^^

2024-03-05 13:38 UTC, LouiseLeroux1992 commented on components/inputs/parentInput.module.css
comment ça ?

2024-03-05 13:41 UTC, Archors commented on components/inputs/parentInput.module.css
C'est du code de parentInput que je te demande de modifier c'est pour ca que je dit ca
de mettre sur plusieurs lignes

2024-03-05 13:42 UTC, LouiseLeroux1992 commented on components/inputs/parentInput.module.css
ah oui j'ai fait ça partout du coup 👍

2024-03-05 14:48 UTC, Archors approved these changes

2024-03-05 14:49 UTC, merged