App 1429 input number
bureaux-a-partager/morning-react-ui pull request #15
Opened 2024-03-05 15:11 UTC by LouiseLeroux1992

add number input component (based on the bottindmin similar numberInput component)

2024-03-05 15:20 UTC, Casimor approved these changes
12 commits pour 5 fichiers, ca fait un peu beaucoup 😅

2024-03-05 15:52 UTC, LouiseLeroux1992 commented
> 12 commits pour 5 fichiers, ca fait un peu beaucoup 😅

2024-03-06 10:12 UTC, Archors requested changes
Revoir la manière de récupérer les inputs dans le parent (je l'ai déjà dit a l'oral mais au moins c'est personne merge cette PR :) )

2024-03-07 08:36 UTC, dellamowica requested changes
des petites optimisations de code et du nettoyage à faire, à voir si on peut configurer eslint pour accepter les ++ et -- sur les variables, ça serait pas mal

2024-03-07 08:36 UTC, dellamowica commented on app/inputs/page.tsx
> +  console.log(value);
à enlever ;-)

2024-03-07 08:36 UTC, dellamowica commented on app/inputs/page.tsx
> +  console.log(numberValue);
that too

2024-03-07 08:36 UTC, dellamowica commented on components/inputs/inputNumber.tsx
> +      }
```suggestion
      if (newValue === '') {
        setInputValue(NaN);
        return;
      }
      const parsedValue = parseInt(newValue, 10);
      if (!isNaN(parsedValue)) {
        validateAndSet(parsedValue);
      }
```

2024-03-07 08:36 UTC, dellamowica commented on components/inputs/inputNumber.tsx
> +      }
```suggestion
      if (!(event.key === 'ArrowUp' || event.key === 'ArrowDown')) {
         return; // leave early
      }
      event.preventDefault();
      const testedValue = getValidValue(inputValue);
      let newValue = isNaN(testedValue) ? 0 : testedValue;
      
      newValue = event.key === 'ArrowUp' ? newValue + 1 : newValue - 1;

      validateAndSet(newValue);
```

2024-03-07 10:54 UTC, Archors requested changes

2024-03-07 10:54 UTC, Archors commented on components/inputs/inputNumber.tsx
> +type InputProps = {
Ce serait cool de faire un type pour l'import qui soit un peu en commun avec les autres
Genre il y a énormément de props en commun entre le InputText et l'InputNumber

2024-03-07 10:55 UTC, Archors commented on components/inputs/inputNumber.tsx
> +
Pourquoi tu sautes une ligne ici ?

2024-03-07 14:02 UTC, geoffster-bap approved these changes

2024-03-07 14:21 UTC, Archors approved these changes

2024-03-07 14:23 UTC, merged