multi select
bureaux-a-partager/morning-react-ui pull request #22
Opened 2024-03-11 17:39 UTC by Archors

2024-04-02 14:00 UTC, Casimor approved these changes

2024-04-03 09:12 UTC, dellamowica requested changes
merci de respecter les conventions de codage pour produire du code lisible.
faire en sorte de nommer les variables pour que le code ait un sens.

2024-04-03 09:12 UTC, dellamowica commented on components/inputs/selects/hooks/useMultiSelect.ts
> +    e: React.KeyboardEvent<HTMLInputElement | HTMLDivElement>,
```suggestion
    e: KeyboardEvent<HTMLInputElement | HTMLDivElement>,
```

2024-04-03 09:12 UTC, dellamowica commented on components/inputs/selects/hooks/useMultiSelect.ts
> +    e: React.KeyboardEvent<HTMLInputElement | HTMLDivElement>,
```suggestion
    e: KeyboardEvent<HTMLInputElement | HTMLDivElement>,
```

2024-04-03 09:12 UTC, dellamowica commented on components/inputs/selects/hooks/useMultiSelect.ts
> +    e: React.KeyboardEvent<HTMLInputElement | HTMLDivElement>, // Event from the keyboard action
```suggestion
    e: KeyboardEvent<HTMLInputElement | HTMLDivElement>, // Event from the keyboard action
```

2024-04-03 09:12 UTC, dellamowica commented on utils/selectionStateUtils.ts
> +  if (selectionState === undefined) return '';
```suggestion
  if (selectionState === undefined) {
      return '';
  }
```

2024-04-03 09:12 UTC, dellamowica commented on utils/selectionStateUtils.ts
> +
```suggestion
```

2024-04-03 09:12 UTC, dellamowica commented on utils/selectionStateUtils.ts
> +  if (!state2) return updatedState;
```suggestion
  if (!state2) {
      return updatedState;
  }
```

2024-04-03 09:12 UTC, dellamowica commented on utils/selectionStateUtils.ts
> +      keysToAdd.push(key);
```suggestion
      updatedState[key] = true;
```
j'ai l'impression que ça serait la même chose non?

2024-04-03 09:12 UTC, dellamowica commented on utils/selectionStateUtils.ts
> +  });
```suggestion
```

2024-04-03 09:12 UTC, dellamowica commented on utils/selectionStateUtils.ts
> +  state2: SelectionState | undefined,
```suggestion
  state1: SelectionState | undefined,
  state2: SelectionState | undefined,
```

trouver des noms de variables qui donnent un sens à ce que ça fait.

2024-04-03 09:12 UTC, dellamowica commented on utils/selectionStateUtils.ts
> +  if (!(selectionState && cursorPosition)) return null;
```suggestion
  if (!(selectionState && cursorPosition)) {
      return null;
  }
```

2024-04-03 09:59 UTC, Archors commented on components/inputs/selects/hooks/useMultiSelect.ts
> +        (Object.keys(filteredOptions).length + +displaySelectAll);
C'est une notation qui permet de transformer un booleen en number 
false = 0 et true = 1

2024-04-03 12:48 UTC, dellamowica commented on components/inputs/selects/hooks/useMultiSelect.ts
> +        (Object.keys(filteredOptions).length + +displaySelectAll);
ha ouais! pour que typescript se calme :-P parce qu'en JS, number + bool fait une conversion automatique en number + number(0 ou 1)

2024-04-03 14:06 UTC, Archors commented on components/inputs/selects/hooks/useMultiSelect.ts
> +    };
J'ai pas trouver d'autres moyen de faire ca sans listeners
Parcontre je peux créer le listener seulement quand le dropdown s'active et le nettoyer une fois que le dropdown est fermé

2024-04-03 16:07 UTC, LouiseLeroux1992 approved these changes

2024-04-03 16:07 UTC, LouiseLeroux1992 commented on components/inputs/selects/MultiSelect.tsx
> +            styleCheckbox={{ padding: '6px 10px', cursor: 'pointer' }}
Il y a sûrement une bonne raison, mais je ne comprends pas trop pourquoi le style est ici plutôt que sur une classe css ?

2024-04-04 12:40 UTC, LouiseLeroux1992 approved these changes

2024-04-04 15:43 UTC, dellamowica requested changes

2024-04-04 15:43 UTC, dellamowica commented on components/inputs/selects/hooks/useMultiSelect.ts
> +  }, [maxHeight]);
```suggestion
```

2024-04-09 12:33 UTC, merged