[UTILS]: Add Toaster
bureaux-a-partager/morning-react-ui pull request #24
Opened 2024-03-12 15:44 UTC by Casimor

2024-03-12 16:05 UTC, LouiseLeroux1992 commented on components/utils/toast.module.css
> +    background-color: #CC0905;
```suggestion
    background-color: var(--brick);
```

2024-03-12 16:06 UTC, LouiseLeroux1992 commented on components/utils/toast.module.css
> +    background-color: #119C2B;
```suggestion
    background-color: var(--forest);
```

2024-03-13 13:03 UTC, Archors commented on components/utils/Toast.tsx
> +export const Toast: React.FC<ToastProps> = ({ type, onClose, message }) => {
Cohérence entre les différents composants : 
```suggestion
export const Toast = ({ type, onClose, message }: ToastProps) => {
```

2024-03-13 13:06 UTC, Archors commented on components/utils/Toast.tsx
> +import React, { useEffect } from 'react';
Avec la suppression en dessous import de React inutile
```suggestion
import { useEffect } from 'react';
```

2024-03-14 10:16 UTC, geoffster-bap requested changes

2024-03-14 10:16 UTC, geoffster-bap commented on components/Context/ToastContext.tsx
> +    const id = Math.random().toString(36).slice(2, 11);
Est-ce qu'on installerait pas une lib uuid pour faire ce taffe ?

2024-03-14 10:16 UTC, geoffster-bap commented on components/utils/Toast.tsx
> +    }, 3000);
On se donne le droit de régler la durée d'affichage du toaster ?

2024-03-14 10:16 UTC, geoffster-bap commented on components/utils/Toast.tsx
> +      : 'https://cdn.morning.fr/icons/cross.svg';
Pourquoi on n'importe pas directe ces svg dans la lib ? 
Ya pas un risque de ne pas pouvoir accéder au svg en cas d'indispo ?

2024-03-14 10:16 UTC, geoffster-bap commented on components/Context/ToastContext.tsx
> +export type ToastMessageType = 'success' | 'error';
Pas de warning ?

2024-03-14 10:51 UTC, LouiseLeroux1992 commented on components/utils/Toast.tsx
> +      : 'https://cdn.morning.fr/icons/cross.svg';
Je crois que l'idée c'était d'avoir toutes les images dans le bucket GCP pour pas alourdir la lib

2024-03-14 12:58 UTC, geoffster-bap commented on components/utils/Toast.tsx
> +      : 'https://cdn.morning.fr/icons/cross.svg';
ouais mais on est sur des svg, c'est pas la mort en terme de place non plus
Là, ya potentiellement un risque d'avoir une lib qui n'affiche pas les images parce qu'une URL random ne répond pas.

2024-03-14 16:22 UTC, Archors commented on components/Context/ToastContext.tsx
> +export type ToastMessageType = 'success' | 'error';
C'est le toaster du bottin, qui n'avait pas besoin de warning
A voir avec le produit je pense

2024-03-14 16:25 UTC, Archors commented on components/Context/ToastContext.tsx
> +    const id = Math.random().toString(36).slice(2, 11);
Je viens de trouver ca: https://react.dev/reference/react/useId
je me demande si on peut pas s'en servir

2024-03-15 15:25 UTC, dellamowica requested changes

2024-03-15 15:25 UTC, dellamowica commented on components/Context/ToastContext.tsx
> +    const id = Math.random().toString(36).slice(2, 11);
il vaut mieux oui parce que random n'est pas si random

2024-03-18 13:39 UTC, geoffster-bap commented on components/Context/ToastContext.tsx
> +    const id = Math.random().toString(36).slice(2, 11);
pas mal

2024-03-20 15:49 UTC, Casimor commented on components/Context/ToastContext.tsx
> +    const id = Math.random().toString(36).slice(2, 11);
pas possible d'utiliser `useId` dans le useCallBack donc j'ai utilise une lib :(

2024-03-21 13:02 UTC, geoffster-bap approved these changes

2024-03-21 14:58 UTC, dellamowica approved these changes

2024-03-21 14:59 UTC, merged