[BUTTON]: Add Link button without border
bureaux-a-partager/morning-react-ui pull request #33
Opened 2024-03-21 08:22 UTC by Casimor

2024-03-21 09:14 UTC, LouiseLeroux1992 approved these changes

2024-03-22 17:49 UTC, Archors requested changes

2024-03-22 17:49 UTC, Archors commented on components/buttons/linkButton.module.css
> +/* Content and icon styling */
On dirait un commentaire chatgpt hehe

2024-03-22 17:49 UTC, Archors commented on components/buttons/linkButton.module.css
> +}
Le saut de ligne en fin de fichier 👟

2024-03-22 17:49 UTC, Archors commented on components/buttons/linkButton.module.css
> +.linkButton.hover,
Pourquoi t'as une classe .hover en plus de :hover ?
Il faut que ca puisse être en état hover de base sans que la souris hover ? SI c'est juste pour le display sur la page d'affichage je pense que c'est superflu

2024-03-22 17:49 UTC, Archors commented on components/buttons/linkButton.module.css
> +    line-height: 20px;
La line height depend de la size je crois, il me semble pas qu'il faille la mettre en dur

2024-03-22 17:49 UTC, Archors commented on components/buttons/linkButton.module.css
> +}
Je sais que ca été fait comme ca ailleurs mais je vais proposer autre chose 
je trouve ca plus propre que de créer 150 classes css pour toutes les tailles et d'être libre sur le nombre de tailles (je pense que je changerai ailleurs si on valide ca)
la suggestion est sur du typescript et pas du css ducoup

```
style={{
        lineHeight: `${sizeToNumber(size)}px`,
        fontSize: `${sizeToFontSize(size)}px`,
      }}
```

en gros j'ai créer une fonction une fonction dans enum.ts
```
export function sizeToFontSize(size: Size): number {
  switch (size) {
    case Size.xl:
      return 18;
    case Size.l:
      return 16;
    case Size.m:
      return 14;
    case Size.s:
      return 12;
    case Size.xs:
      return 10;
  }
}

```

2024-03-26 10:55 UTC, dellamowica approved these changes

2024-03-26 15:35 UTC, Archors requested changes

2024-03-26 15:41 UTC, Archors approved these changes

2024-03-26 15:43 UTC, merged