checkbox & multi checkbox
bureaux-a-partager/morning-react-ui pull request #34
Opened 2024-03-24 22:48 UTC by Archors

2024-03-25 10:51 UTC, LouiseLeroux1992 approved these changes

2024-03-25 10:51 UTC, LouiseLeroux1992 commented on utils/selectionStateUtils.ts
> +    const { [lastKey]: _, ...remainingSelectioNState } = selectionStateToRemove;
c'est une faute de frappe le N majuscule à selectioN ?

2024-03-25 10:51 UTC, LouiseLeroux1992 commented on utils/selectionStateUtils.ts
> +    const { [lastKey]: _, ...remainingSelectioNState } = selectionStateToRemove;
```suggestion
    const { [lastKey]: _, ...remainingSelectionState } = selectionStateToRemove;
```

2024-03-25 10:51 UTC, LouiseLeroux1992 commented on utils/selectionStateUtils.ts
> +    return remainingSelectioNState;
```suggestion
    return remainingSelectionState;
```

2024-03-25 12:56 UTC, Casimor commented on components/inputs/checkboxes/MultiCheckbox.tsx
> +  selectAllLabel = 'Tout selectionner',
Tout sélectionner ?

2024-03-25 13:00 UTC, Casimor commented on utils/selectionStateUtils.ts
> +    const { [lastKey]: _, ...remainingSelectioNState } = selectionStateToRemove;
oui

2024-03-25 13:51 UTC, Casimor approved these changes

2024-03-25 15:55 UTC, geoffster-bap approved these changes

2024-03-25 16:28 UTC, dellamowica requested changes

2024-03-25 16:28 UTC, dellamowica commented on components/inputs/checkboxes/Checkbox.tsx
> +      </span>
pour être cohérent on devrait avoir le SVG en fichier externe comme dans le reste du projet.

2024-03-26 10:56 UTC, dellamowica approved these changes

2024-03-26 13:27 UTC, merged