[RADIO]: Add Radio
bureaux-a-partager/morning-react-ui pull request #36
Opened 2024-03-28 13:06 UTC by Casimor

2024-03-28 14:14 UTC, LouiseLeroux1992 approved these changes

2024-03-28 14:14 UTC, LouiseLeroux1992 commented on components/inputs/radio/Radio.tsx
> +        fontSize: `${sizeToFontSize(size)}px`,
Du coup suite à la discussion de ce matin je comprends plus, on utilise ça ou il faut que tout soit dans le CSS ?

2024-03-28 14:22 UTC, Casimor commented on components/inputs/radio/Radio.tsx
> +        fontSize: `${sizeToFontSize(size)}px`,
Je rebase quand la PR d'Antoine sera mergee

2024-03-28 14:37 UTC, LouiseLeroux1992 commented on components/inputs/radio/Radio.tsx
> +        fontSize: `${sizeToFontSize(size)}px`,
oki 👍

2024-03-29 09:20 UTC, Archors commented on components/inputs/radio/Radio.tsx
> +        fontSize: `${sizeToFontSize(size)}px`,
Ouais les fonctions doivent servir que pour les Image next ducoup

2024-03-29 09:28 UTC, Archors requested changes

2024-03-29 09:28 UTC, Archors commented on components/inputs/radio/MultiRadio.tsx
> +  options: SelectionState;
J'aime cette réutilisation du type

2024-03-29 09:28 UTC, Archors commented on components/inputs/radio/Radio.tsx
> +        className={`${styles.label} ${disabled ? 'disabled' : 'pointer'}`}
Je sais que cette ligne est a moi mais je vais quand meme te faire le retour ahah
utilise la librairie classnames pour mettre les classes je le fais d'habitude mais j'ai du oublier 😢 
En plus tu l'as fait juste au dessus 😆

2024-03-29 09:28 UTC, Archors commented
J'adore ton code

2024-04-12 08:44 UTC, dellamowica approved these changes

2024-04-12 08:55 UTC, merged