modal, useModal hook and readme doc
bureaux-a-partager/morning-react-ui pull request #49
Opened 2024-04-16 09:55 UTC by LouiseLeroux1992

2024-04-16 13:40 UTC, dellamowica requested changes

2024-04-16 13:40 UTC, dellamowica commented on components/modal/Modal.tsx
> +                onClick={hide}
en réalité on suppose ici que le métier qui sera fait au clic est de cacher la modale mais c'est pas certain. ce "hide" peut être n'importe quoi en réalité. 
il vaudrait mieux nommer ça handleButtonClick, ce qui serait plus parlant et générique

2024-04-16 14:40 UTC, Casimor approved these changes

2024-04-17 09:35 UTC, LouiseLeroux1992 commented on components/modal/Modal.tsx
> +                onClick={hide}
j'ai rajouté un footer avec des boutons qui ont chacun leur onClick, mais j'ai laissé celui-là avec le hide comme c'est la croix qui ferme la modale

2024-04-17 15:55 UTC, dellamowica approved these changes

2024-04-18 09:16 UTC, dellamowica approved these changes

2024-04-18 09:18 UTC, merged